CREATE TABLE NATION (
		KEY		SERIAL,
		NAME			CHAR(25),
		DESCRIPTION		VARCHAR(152)
	);

CREATE TABLE CUSTOMER (
		KEY		SERIAL,
		NAME			VARCHAR(25),
		ADDRESS		VARCHAR(40),
    PHONE			CHAR(15),
		NATIONKEY		BIGINT NOT NULL
	);

ALTER TABLE CUSTOMER ADD PRIMARY KEY (KEY);
ALTER TABLE NATION ADD PRIMARY KEY (KEY);

\echo 'LOADING nation'
\i load_nation.sql
\echo 'LOADING customer'
\i load_customer.sql