CREATE TABLE NATION (
		ID				SERIAL,
		NAME			CHAR(25),
		DESCRIPTION		VARCHAR(152)
	);

CREATE TABLE CUSTOMER (
		ID				SERIAL,
		NAME			VARCHAR(25),
		MARRIED			BOOLEAN,
    	PHONE			CHAR(15),
		NATION_ID		BIGINT NOT NULL
	);

ALTER TABLE CUSTOMER ADD PRIMARY KEY (ID);
ALTER TABLE NATION ADD PRIMARY KEY (ID);

\echo 'LOADING nation'
\i load_nation.sql
\echo 'LOADING customer'
\i load_customer.sql